# Generated by Django 3.2 on 2021-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Marks', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
