# Generated by Django 3.2 on 2021-05-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Balance', models.IntegerField()),
                ('Mobile', models.IntegerField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Password', models.IntegerField(max_length=100)),
            ],
        ),
    ]
